### ISSUE TITLE
Shapefile creator not running

### ISSUE THREAD

**Issue by volpatoo** [TiagoOlivoto/plimanshiny#14]
Something is going wrong when import orthomosaic and then try to create a new shapefile.
Old plimanshiny version was working well, but the new one which now has a different way to import data has some issue.

```r
Warning: Error in shapefile_build: unused argument (layout = input$plotlayout)
  3: runApp
  2: print.shiny.appobj
  1: <Anonymous>
```

**Comment by TiagoOlivoto** [comment]
Have you installed the dev version of pliman? shapefile_build() comes from there.

**Comment by volpatoo** [comment]
Thanks a lot! The issue was solved by running and installing pliman R package with:
pak::pkg_install("TiagoOlivoto/pliman")
