### ISSUE TITLE
Error al instalar plimanshiny

### ISSUE THREAD

**Issue by santiago77182** [TiagoOlivoto/plimanshiny#15]
Buenas tardes, estoy teniendo inconvenientes para ejecutar PlimanShiny, me sale este error
![Captura de pantalla 2024-05-24 142017](https://github.com/TiagoOlivoto/plimanshiny/assets/140027738/c82302c2-4ece-4158-aad1-60341d0fcdee)
y la ventana de plimanshiny se queda cargando pero nunca ejecuta el programa...
como podre solucionar este problema?

**Comment by TiagoOlivoto** [comment]
Olá! Certifique que você também instalou o pacote pliman do GitHub, usando a mesma função do pacote pak.

Ele é preciso para que o plimanshiny seja executado corretamente

**Comment by aldepas** [comment]
Hola, magnífico trabajo. Yo también tengo en mismo problema. Las líneas que he usado para realizar la instalación son las siguientes:

install.packages("pak")
pak::pkg_install("TiagoOlivoto/pliman")
pak::pkg_install("TiagoOlivoto/plimanshiny")
library(plimanshiny)
run_app()

Mi sistema es Windows 10 y Rstudio, previamente he instalado Rtools.

Muchas gracias

**Comment by TiagoOlivoto** [comment]
Olá @aldepas , conseguiu instalar?
Caso não, tente instalar um outro pacote do github, como ggplot2 e veja se o problema persiste.

**Comment by TiagoOlivoto** [comment]
New issues can now be filled at https://github.com/NEPEM-UFSC/plimanshiny
