### ISSUE TITLE
Mapview is not displaying at Index and Analyze tabs

### ISSUE THREAD

**Issue by volpatoo** [TiagoOlivoto/plimanshiny#4]
The imported orthomosaic is not displayed in the "Syncked maps" canvas view in the "Index" and "Analyze" tabs.
There is something loading, but the orthomosaic does not show up. 

Additionally, when users try to run the vegetation indexes after choosing it and click on "Compute indexes!" there is an error message, however, the user still downloads the .tif image using the output VI selected previously. 

```r
Warning: Error in <Anonymous>: unable to find an inherited method for function ‘mapView’ for signature ‘"SpatRaster"’
  110: stop
  109: <Anonymous>
  108: mapView
  107: mapview
  103: mapview::mapview
  102: mosaic_view
   99: renderUI [C:/temp_plimanshiny/plimanshiny-master/R/mod_indexes.R#161]
   98: func
   85: renderFunc
   84: output$indexes_1-indexsync
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
```

![image](https://github.com/TiagoOlivoto/plimanshiny/assets/44096217/5516243a-61aa-4cab-b446-466ef5f157b7)

**Comment by TiagoOlivoto** [comment]
Fixed after updating mapview
