### ISSUE TITLE
SAVI vegetation index RGB or MS?

### ISSUE THREAD

**Issue by volpatoo** [TiagoOlivoto/plimanshiny#9]
SAVI vegetation index is not working well. For some reason, this index has been called MS when selecting RGB indexes. I also noticed that SAVI is present in both, RGB and MS. In this case, a unique name should be given to MS or RGB. 

![image](https://github.com/TiagoOlivoto/plimanshiny/assets/44096217/5e988b32-b878-4b57-ab1b-e4c23e39df09)

**Comment by TiagoOlivoto** [comment]
This was just fixed in a previous commit.. Please, download the dev version to see the changes
